#pragma once


#define TEXT_WINDOW_CLASS _T("ASR-1388")

#define COLOR_WINDOW_BACKGROUND RGB(0, 0, 0)
#define COLOR_WINDOW_FOREGROUND RGB(236, 64, 64)
#define COLOR_LED_OFF			RGB(52, 52, 52)
#define COLOR_LED_ON			COLOR_WINDOW_FOREGROUND
